apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
          - server
          - /data1
          - /data2
          - /data3
          - /data4
        env:
        - name: MINIO_ACCESS_KEY
          value: "admin"
        - name: MINIO_SECRET_KEY
          value: "admin123"
        ports:
        - containerPort: 9000
        - containerPort: 9090
        volumeMounts:
        - name: data1
          mountPath: /data1
        - name: data2
          mountPath: /data2
        - name: data3
          mountPath: /data3
        - name: data4
          mountPath: /data4
      volumes:
      - name: data1
        persistentVolumeClaim:
          claimName: minio-pvc1
      - name: data2
        persistentVolumeClaim:
          claimName: minio-pvc2
      - name: data3
        persistentVolumeClaim:
          claimName: minio-pvc3
      - name: data4
        persistentVolumeClaim:
          claimName: minio-pvc4
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    port: 9090
    targetPort: 9000
    protocal: TCP
  type: ClusterIP